# permissions for end users to edit logmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logmonitor-editor-role
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - logmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - logmonitors/status
  verbs:
  - get
