apiVersion: logmonitor.monitoring.coreos.com/v1
kind: LogMonitor
metadata:
  name: logmonitor-sample
spec:
  # Add fields here
  labels: 
    linkPrefix: link_prefix
    application: application
    alarmSource: alarm_source
    alarmContent: alarmContent
    metricName: metricName
    metricInstanceId: metricInstanceId
    strategyName: name
    strategyId: logmonitor-sample
    contact: contact
    containerName: mantis-api
  dsl: '{"query":{"bool":{"must":[{"term":{"kubernetes.container.name":"mantis-api"}},{"match_phrase":{"message":"File"}}]}}}'
  promql: vector(1)
  duration: 20m
  contactType: email
  contactValue: linzhiqiang@gridsum.com
  extend: extend
